version: "3"

services: 
  db: 
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: "postgres:latest"
    ports: 
      - "5432:5432"