version: "3"

services: 
  db:
    container_name: "db"
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    volumes: 
      - ./db/sqlc:/db_schema
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"