// Code generated by mockery v2.32.2. DO NOT EDIT.

package mock

import (
	context "context"
	model "forbole_code_test/model"

	mock "github.com/stretchr/testify/mock"
)

// UserProvider is an autogenerated mock type for the UserProvider type
type UserProvider struct {
	mock.Mock
}

type UserProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *UserProvider) EXPECT() *UserProvider_Expecter {
	return &UserProvider_Expecter{mock: &_m.Mock}
}

// GetRandomUser provides a mock function with given fields: ctx
func (_m *UserProvider) GetRandomUser(ctx context.Context) (*model.User, error) {
	ret := _m.Called(ctx)

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProvider_GetRandomUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomUser'
type UserProvider_GetRandomUser_Call struct {
	*mock.Call
}

// GetRandomUser is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserProvider_Expecter) GetRandomUser(ctx interface{}) *UserProvider_GetRandomUser_Call {
	return &UserProvider_GetRandomUser_Call{Call: _e.mock.On("GetRandomUser", ctx)}
}

func (_c *UserProvider_GetRandomUser_Call) Run(run func(ctx context.Context)) *UserProvider_GetRandomUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserProvider_GetRandomUser_Call) Return(_a0 *model.User, _a1 error) *UserProvider_GetRandomUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserProvider_GetRandomUser_Call) RunAndReturn(run func(context.Context) (*model.User, error)) *UserProvider_GetRandomUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserProvider creates a new instance of UserProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserProvider {
	mock := &UserProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
