// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package sqlc_generated

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    first_name,
    last_name,
    dob,
    address
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, first_name, last_name, dob, address
`

type CreateUserParams struct {
	FirstName sql.NullString
	LastName  sql.NullString
	Dob       sql.NullTime
	Address   pqtype.NullRawMessage
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Dob,
		arg.Address,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Dob,
		&i.Address,
	)
	return i, err
}
